#!/bin/bash
# NA producers group
PUSHOVER_USER_KEY=${PUSHOVER_USER_KEY:+gYR1YGR9sK7YtK2e52bgrNvKH1Daho}

curl -X POST $PUSHOVER_URI \
	--data "token=${PUSHOVER_TOKEN}" \
	--data "user=${PUSHOVER_USER_KEY}" \
	--data-urlencode "message=$*" \
	--data-urlencode "url=http://www.noagendastream.com/" \
	--data-urlencode "url_title=Listen live"
